### ISSUE TITLE
Keyboard view control improvements

### ISSUE THREAD

**Issue by dronir** [abetusk/bleepsix#78]
Since I'm an Apple trackpad user (ref #77 and abetusk/www.meowcad.com#24 ), I'd be happy for at least these two improvements: 
- Have the arrow keys move the view around, because right-clicking and dragging on a mac trackpad is a bit awkward (the right-click is made by clicking with two fingers on the trackpad), so doing it a lot is tedious.
- Have a hotkey like in LTSpice that resets the view (basically instantly zooms and shifts to fit the entire circuit onto the screen). I find this helps a lot in navigating around the circuit.

**Comment by abetusk** [comment]
Arrow movement should already be in place.  Use the arrow keys to move around.  Let me know if that doesn't work.

Resetting the view is a good idea.  Any preference for what the hot-key should be?

**Comment by dronir** [comment]
The arrow keys do not seem to work in the schematic editor, but they do work in the board editor. I didn't really explore the board editor much yet.

In LTSpice the hotkey for the view reset is the space bar, so I'm used to that, but they hotkeys in LTSpice are are bit unorthodox in general, so not sure if that's the best idea.

**Comment by dronir** [comment]
Since your snapshot tool only grabs a certain part of the screen, maybe the view reset should zoom so that the entire circuit or board is within that view. That would probably be useful.

**Comment by abetusk** [comment]
OK, thanks, hadn't realized the schematic didn't have the arrow move.  I'll get to that as well.

**Comment by abetusk** [comment]
Fixed and deployed.  The '0' key is the one that's used to recenter the view.  I'm happy to change the hot-key but in the future I think I'm going to try and expose some configuration options for people so they can set it to preference.

Panning should also be working for the schematic portion.

The recenter might still need some tweaking (which should also maybe be parameters to the customization) so feel free to open another issue in the meantime.

https://github.com/abetusk/bleepsix/commit/b932bd70300281c73247adc827e97edb43bfa485
